feat: add option to ignore cache
wix-incubator/detox-copilot pull request #23
Opened 2024-10-21 11:55 UTC by LironMShemen

- Introduced a new environment variable to bypass cache.
- Updated README to include usage instructions.

2024-10-21 12:50 UTC, asafkorem requested changes
round 2

2024-10-21 12:50 UTC, asafkorem commented on README.md
> +process.env.COPILOT_OVERRIDE_CACHE = "1"
so both "1" and "true" are supported? are you sure?

2024-10-21 12:50 UTC, asafkorem commented on README.md
> +process.env.COPILOT_OVERRIDE_CACHE = "1"
also, it's not a bash script but JS script

2024-10-21 12:50 UTC, asafkorem commented on README.md
> +process.env.COPILOT_OVERRIDE_CACHE = "1"
replace it with `export COPILOT_OVERRIDE_CACHE=true`

2024-10-21 12:50 UTC, asafkorem commented on src/actions/StepPerformer.ts
> +        if (process.env.COPILOT_OVERRIDE_CACHE != "true" && this.cache.has(cacheKey)) {
why `!=` and not `!==`? 🙂

2024-10-21 12:50 UTC, asafkorem commented on src/actions/StepPerformer.ts
> +        if (process.env.COPILOT_OVERRIDE_CACHE != "true" && this.cache.has(cacheKey)) {
can you write a test for that? add it to `StepPerformer.test.ts`

2024-10-21 14:49 UTC, LironMShemen commented
I changed my code according to the comments. Mistakenly, I did the commit with amend.

2024-10-22 06:05 UTC, asafkorem commented
Actually, squashing (or in this case - amending) commit changes after a code review is actually a great practice as it keeps the history clean and focused on the **final**, relevant changes. 

For larger reviews, I do prefer separate commits to show the specific fixes from the code review, and then once everything is approved, we can squash them into more meaningful, contained commits.

However, since that's a small change, I'm perfectly fine with the amend approach here, it keeps things clean and simple

2024-10-22 10:48 UTC, asafkorem requested changes

2024-10-22 10:48 UTC, asafkorem commented on src/actions/StepPerformer.test.ts
> +
```suggestion
```

2024-10-22 10:48 UTC, asafkorem commented on src/actions/StepPerformer.ts
> +
```suggestion
```

2024-10-22 13:13 UTC, merged